development:
  adapter: postgresql
  encoding: unicode
  database: hound_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: hound_test
  pool: 5

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %> #This is the environment variable created by our Dokku command earlier
  encoding: unicode
  pool: 5
